name: Python Docker Base Image CI

on:
  workflow_dispatch:
    inputs:
      package_name:
        description: package name to use
        required: true
        default: "project-template"

jobs:
  cpu-version:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push base image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./
          file: ./docker/cpu/Dockerfile
          tags: |
            ghcr.io/makinarocks/${{ github.event.inputs.package_name }}:latest
            ghcr.io/makinarocks/${{ github.event.inputs.package_name }}:${{ steps.short-sha.outputs.sha }}
  gpu-version:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create short SHA
        uses: benjlevesque/short-sha@v1.2
        id: short-sha
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push python:base-gpu
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./
          file: ./docker/gpu/Dockerfile
          tags: |
            ghcr.io/makinarocks/${{ github.event.inputs.package_name }}-gpu:latest
            ghcr.io/makinarocks/${{ github.event.inputs.package_name }}-gpu:${{ steps.short-sha.outputs.sha }}
          build-args: |
            BASE_CONTAINER=ghcr.io/makinarocks/python:3.8-base-gpu
